---
# tasks file for wordpress
- name: Download do Wordpress
  get_url:
    url=https://wordpress.org/latest.tar.gz
    dest=/tmp/wordpress.tar.gz
    validate_certs=no

- name: Descompactando o Wordpress
  unarchive: src=/tmp/wordpress.tar.gz dest=/var/www/html/wodpress copy=no
  become: yes

- name: Alterando a Configuração do Nginx
  lineinfile:
    dest=/etc/nginx/sites-enabled/default
    regexp="^\s*root\s+/var/www/html;"
    line="root /var/www/html/wordpress;"
  notify: 
    - restart nginx

- name: Criando o Arquivo de Configuração Padrão Wordpress
  command: mv /var/www/html/wordpress/wp-config-sample.php /var/www/html/wordpress/wp-config.php
  become: yes