---
# tasks file for mysql
# - name: Criando o Banco de Dados no mysql
#   mysql_db: name={{ wp_mysql_db }} state=present
#   become: yes

- name: Criando o Banco de Dados no mysql
  mysql_db:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: {{ wp_mysql_db }}
    state: present
    become: yes

- name: Criando o Usuário do mysql
  mysql_user: 
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: {{ wp_mysql_user }}
    password: {{ wp_mysql_password }}
    priv: "*.*:ALL"
    host: 'localhost'
    state: present
  become: yes


# - name: Criando o Usuário do mysql
#   mysql_user:
#     name={{ wp_mysql_user }}
#     passwodr={{ wp_mysql_password }}
#     priv=*.*:ALL
#   become: yes
