---
- name: Update All Packages
  ansible.builtin.apt:
    update_cache: yes
- name: Upgrade All Packages
  ansible.builtin.apt:
    upgrade: yes
  notify: 
    - "Restart server"
    - "Wait for server to restart"