---
# tasks file for server
- name: Adicionando Repositorio do PHP 8.1
  apt_repository:
    repo: ppa/ondrej/php
    state: present
  become: true

- name: Garantindo Update do Servidor
  apt: update_cache=yes cache_valid_time=3600
  become: yes

- name: Instalando as dependência
  apt: name={{ packages }} state=present
  become: yes
  vars:
    packages:
    - nginx
    - mysql-server
    - php8.1
    - php8.1-mysql
    - python-mysqldb