---
# tasks file for wordpress
- name: Download do Wordpress
  get_url:
    url=https://wordpress.org/latest.tar.gz
    dest=/tmp/wordpress.tar.gz
    validate_certs=no

- name: Descompactando o Wordpress
  unarchive: src=/tmp/wordpress.tar.gz dest=/var/www/html/wodpress copy=no
  become: yes

- name: Alterando a Configuração do Nginx
  lineinfile:
    dest=/etc/nginx/sites-enabled/default
    regexp="^\s*root\s+/var/www/html;"
    line="root /var/www/html/wordpress;"
  notify: 
    - restart nginx

- name: Criando o Arquivo de Configuração padrão Wordpress
  command: mv /var/www/html/wordpress/wp-config-sample.php /var/www/html/wordpress/wp-config.php
  become: yes

- name: Update no arquivo de configuração padrão Wordpress
  lineinfile:
    dest=/var/www/html/wordpress/wp-config.php
    regexp="{{ item.regexp }}"
    line="{{ item.line }}"
  with_items:
    - {'regexp': "define\\('DB_NAME', '(.)+'\\);", 'line': "define('DB_NAME', '{{wp_mysql_db}}');"}
    - {'regexp': "define\\('DB_USER', '(.)+'\\);", 'line': "define('DB_USER', '{{wp_mysql_user}}');"}
    - {'regexp': "define\\('DB_PASSWORD', '(.)+'\\);", 'line': "define('DB_PASSWORD', '{{wp_mysql_password}}');"}
  become: yes